import re

content = open("/home/kali/asvs-pro/server.py").read()

new_export = '''@app.route('/api/export/excel', methods=['POST'])
def export_excel():
    from openpyxl.chart import BarChart, Reference, Series
    data = request.json
    results = data.get('categoryResults', {})
    project = data.get('project_name', 'ASVS Analysis')
    wb = Workbook()
    wb.remove(wb.active)

    hf        = PatternFill("solid", fgColor="1F3864")
    hFont     = Font(color="FFFFFF", bold=True, name="Calibri", size=11)
    pass_fill = PatternFill("solid", fgColor="C6EFCE")
    pass_font = Font(color="276221", bold=True, name="Calibri")
    fail_fill = PatternFill("solid", fgColor="FFC7CE")
    fail_font = Font(color="9C0006", bold=True, name="Calibri")
    alt_fill  = PatternFill("solid", fgColor="EEF4FF")
    thin = Border(left=Side(style="thin"),right=Side(style="thin"),
                  top=Side(style="thin"),bottom=Side(style="thin"))
    center = Alignment(horizontal="center", vertical="center", wrap_text=True)
    left   = Alignment(horizontal="left",   vertical="center", wrap_text=True)

    cols   = ["Area","#","ASVS Level","CWE","Verification Requirement",
              "Status","Source Code Reference","Confidence","Tool Used"]
    widths = [22,8,10,8,58,10,40,12,18]

    for cat, cat_data in results.items():
        ws = wb.create_sheet(cat[:31])
        ws.freeze_panes = "A2"
        for ci, cn in enumerate(cols, 1):
            c = ws.cell(row=1, column=ci, value=cn)
            c.fill = hf; c.font = hFont; c.alignment = center; c.border = thin
            ws.column_dimensions[get_column_letter(ci)].width = widths[ci-1]
        ws.row_dimensions[1].height = 30
        for ri, req in enumerate(cat_data.get("reqs", []), 2):
            implemented = req.get("implemented", False)
            status = "Pass" if implemented else "Fail"
            src  = req.get("finding", {}).get("note", "") if req.get("finding") else ""
            conf = req.get("finding", {}).get("confidence", "") if req.get("finding") else ""
            tool = "ASVS Analyzer Pro" if implemented else ""
            vals = [req.get("area",""), req.get("id",""), req.get("level",""),
                    req.get("cwe",""), req.get("requirement",""),
                    status, src, conf, tool]
            row_bg = alt_fill if ri % 2 == 0 else None
            for ci, val in enumerate(vals, 1):
                c = ws.cell(row=ri, column=ci, value=val)
                c.border = thin
                c.alignment = center if ci in [2,3,4,6,8] else left
                if ci == 6:
                    if val == "Pass":
                        c.fill = pass_fill; c.font = pass_font
                    else:
                        c.fill = fail_fill; c.font = fail_font
                elif row_bg:
                    c.fill = row_bg
            ws.row_dimensions[ri].height = 22

    # ASVS Results summary sheet
    ws_r = wb.create_sheet("ASVS Results", 0)
    ws_r.sheet_view.showGridLines = False

    # Title
    ws_r.merge_cells("A1:E1")
    t = ws_r["A1"]
    t.value = f"ASVS Security Assessment Report — {project}"
    t.font  = Font(name="Calibri", size=14, bold=True, color="1F3864")
    t.alignment = Alignment(horizontal="center", vertical="center")
    t.fill  = PatternFill("solid", fgColor="DCE6F1")
    ws_r.row_dimensions[1].height = 34

    ws_r.merge_cells("A2:E2")
    s = ws_r["A2"]
    s.value = "Generated by ASVS Analyzer Pro  |  OWASP ASVS 5.0"
    s.font  = Font(name="Calibri", size=9, italic=True, color="7F7F7F")
    s.alignment = Alignment(horizontal="center", vertical="center")
    ws_r.row_dimensions[2].height = 18

    # Blank separator row 3
    ws_r.row_dimensions[3].height = 8

    sum_cols   = ["Security Category","Controls Found","Total Controls","Coverage %","Status"]
    sum_widths = [30,16,16,16,22]
    for ci,(cn,cw) in enumerate(zip(sum_cols,sum_widths),1):
        ws_r.column_dimensions[get_column_letter(ci)].width = cw
        c = ws_r.cell(row=4, column=ci, value=cn)
        c.fill = hf; c.font = hFont; c.alignment = center; c.border = thin
    ws_r.row_dimensions[4].height = 28

    level_styles = {
        "Level 2":  (PatternFill("solid",fgColor="C6EFCE"), Font(color="276221",bold=True,name="Calibri")),
        "Level 1":  (PatternFill("solid",fgColor="FFEB9C"), Font(color="9C6500",bold=True,name="Calibri")),
        "Below L1": (PatternFill("solid",fgColor="FFC7CE"), Font(color="9C0006",bold=True,name="Calibri")),
    }

    total_found=0; total_reqs=0
    chart_cats=[]; chart_found=[]; chart_total=[]
    data_start=5

    for ri,(cat,cd) in enumerate(results.items(), data_start):
        imp=cd.get("implemented",0); tot=cd.get("total",0)
        pct=round((imp/tot)*100) if tot else 0
        total_found+=imp; total_reqs+=tot
        lvl="Level 2" if pct>=70 else "Level 1" if pct>=40 else "Below L1"
        chart_cats.append(cat[:18]); chart_found.append(imp); chart_total.append(tot)
        row_bg = PatternFill("solid",fgColor="EEF4FF") if ri%2==0 else None
        for ci,val in enumerate([cat,imp,tot,f"{pct}%",lvl],1):
            c = ws_r.cell(row=ri,column=ci,value=val)
            c.border=thin
            c.alignment=center if ci>1 else left
            if ci==5:
                lf,lft=level_styles.get(lvl,(None,None))
                if lf: c.fill=lf
                if lft: c.font=lft
            elif row_bg:
                c.fill=row_bg
        ws_r.row_dimensions[ri].height=22

    total_row=data_start+len(results)
    overall=round((total_found/total_reqs)*100) if total_reqs else 0
    for ci,val in enumerate(["TOTAL",total_found,total_reqs,f"{overall}%",""],1):
        c=ws_r.cell(row=total_row,column=ci,value=val)
        c.font=Font(bold=True,name="Calibri",size=11)
        c.border=thin; c.alignment=center if ci>1 else left
        c.fill=PatternFill("solid",fgColor="DCE6F1")
    ws_r.row_dimensions[total_row].height=26

    # Chart data in hidden cols G H I
    chart_row_start=total_row+3
    ws_r.cell(row=chart_row_start-1,column=7,value="Category")
    ws_r.cell(row=chart_row_start-1,column=8,value="Found")
    ws_r.cell(row=chart_row_start-1,column=9,value="Total")
    for i,(cat,f,t) in enumerate(zip(chart_cats,chart_found,chart_total)):
        ws_r.cell(row=chart_row_start+i,column=7,value=cat)
        ws_r.cell(row=chart_row_start+i,column=8,value=f)
        ws_r.cell(row=chart_row_start+i,column=9,value=t)

    n=len(chart_cats)
    chart=BarChart()
    chart.type="bar"; chart.grouping="clustered"
    chart.title="ASVS Controls Coverage by Category"
    chart.x_axis.title="Controls"; chart.y_axis.title="Category"
    chart.style=10; chart.width=22; chart.height=14

    found_ref=Reference(ws_r,min_col=8,max_col=8,min_row=chart_row_start-1,max_row=chart_row_start+n-1)
    total_ref=Reference(ws_r,min_col=9,max_col=9,min_row=chart_row_start-1,max_row=chart_row_start+n-1)
    cats_ref =Reference(ws_r,min_col=7,max_col=7,min_row=chart_row_start,max_row=chart_row_start+n-1)

    ser1=Series(found_ref,title_from_data=True)
    ser2=Series(total_ref,title_from_data=True)
    chart.series.append(ser1); chart.series.append(ser2)
    chart.set_categories(cats_ref)

    ws_r.add_chart(chart,f"A{total_row+3}")

    buf=io.BytesIO()
    wb.save(buf); buf.seek(0)
    return send_file(buf,
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        as_attachment=True, download_name="ASVS-Pro-Report.xlsx")'''

# Replace old export function
pattern = r"@app\.route\('/api/export/excel'.*?return send_file\(buf, mimetype='application/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet',\s*as_attachment=True, download_name='ASVS-Pro-Report\.xlsx'\)"
new_content = re.sub(pattern, new_export, content, flags=re.DOTALL)

if new_content == content:
    print("ERROR: Pattern not matched — trying direct replacement")
    # Find start and end manually
    start = content.find("@app.route('/api/export/excel'")
    end = content.find("@app.route('/api/export/pdf'")
    if start != -1 and end != -1:
        new_content = content[:start] + new_export + "\n\n" + content[end:]
        print("Direct replacement done!")
    else:
        print("Could not find function boundaries")
else:
    print("Regex replacement done!")

open("/home/kali/asvs-pro/server.py", "w").write(new_content)
print("server.py updated successfully!")
